/// Flutter icons CompanionIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CompanionIcons
///      fonts:
///       - asset: fonts/CompanionIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CompanionIcons {
  CompanionIcons._();

  static const _kFontFam = 'CompanionIcons';
  static const String? _kFontPkg = null;

  static const IconData news =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_artworkprofile =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmarkbookmark =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'GenreIcons';
  static const String? _kFontPkg = null;

  static const IconData roleplay =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adventure =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simulator =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puzzle =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strategy =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData action =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
